console.log(addone(5));
// console.log(addTwo(5));  //here we will get error but not in addone
function addone(num1)
{
    return num1+1;
}
const addTwo=function(num2)
{
    return num+2;
}